apiVersion: apps/v1
kind: Deployment
metadata:
  name: santogem-frontend-deploy
spec:
  replicas: 2 # Ye aapki website ke 2 pods banayega taaki site kabhi down na ho
  selector:
    matchLabels:
      app: santogem-frontend
  template:
    metadata:
      labels:
        app: santogem-frontend
    spec:
      containers:
      - name: frontend
        # YAHAN APNI PUSH KI HUI IMAGE KA NAAM DALEIN
        image: testaksregistry2.azurecr.io/santogem_pharma:latest
        ports:
        - containerPort: 80 # Ya wo port jo aapne Dockerfile me Expose kiya hai
---
apiVersion: v1
kind: Service
metadata:
  name: santogem-frontend-svc
spec:
  type: NodePort # Ye website ko cluster ke bahar access karne dega
  selector:
    app: santogem-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005 # Is port par aapki website live hogi